"""Public Game Tracking application API."""

from discord_stats_bot.features.game_tracking.selector import (
    normalize_game_name,
    select_tracked_game,
    tracked_game_from_activity,
)
from discord_stats_bot.features.game_tracking.server_statistics import (
    ServerGameDailyPoint,
    ServerGameSessionSlice,
    ServerGameStatistics,
    ServerGameStatisticsPeriod,
    ServerGameStatisticsRepository,
    ServerGameStatisticsService,
    ServerGameStatisticsWindow,
    ServerGameTopGame,
    ServerGameTopPlayer,
    build_server_game_statistics_window,
)
from discord_stats_bot.features.game_tracking.service import (
    GameBatchRepository,
    GameCheckpointService,
    GameReconciliationService,
    GameTrackingRepository,
    GameTrackingService,
    GuildMemberNotFoundError,
)
from discord_stats_bot.features.game_tracking.statistics import (
    GameSessionSlice,
    GameStatistics,
    GameStatisticsPeriod,
    GameStatisticsRepository,
    GameStatisticsService,
    GameUsageEntry,
    LatestGame,
    LongestGameSession,
)
from discord_stats_bot.features.game_tracking.types import (
    GameActivitySnapshot,
    GameCheckpointResult,
    GameReconciliationResult,
    GameTransitionResult,
    ObservedGame,
    OpenGameSession,
    TrackedGame,
)

__all__ = [
    "GameActivitySnapshot",
    "GameBatchRepository",
    "GameCheckpointResult",
    "GameCheckpointService",
    "GameReconciliationResult",
    "GameReconciliationService",
    "GameTrackingRepository",
    "GameTrackingService",
    "GameTransitionResult",
    "GameSessionSlice",
    "GameStatistics",
    "GameStatisticsPeriod",
    "GameStatisticsRepository",
    "GameStatisticsService",
    "GameUsageEntry",
    "GuildMemberNotFoundError",
    "ObservedGame",
    "OpenGameSession",
    "ServerGameDailyPoint",
    "ServerGameSessionSlice",
    "ServerGameStatistics",
    "ServerGameStatisticsPeriod",
    "ServerGameStatisticsRepository",
    "ServerGameStatisticsService",
    "ServerGameStatisticsWindow",
    "ServerGameTopGame",
    "ServerGameTopPlayer",
    "LatestGame",
    "LongestGameSession",
    "TrackedGame",
    "build_server_game_statistics_window",
    "normalize_game_name",
    "select_tracked_game",
    "tracked_game_from_activity",
]
