"""Rules v1 application API."""

from discord_stats_bot.features.rules.compliance import (
    RulesComplianceRepository,
    RulesComplianceService,
)
from discord_stats_bot.features.rules.service import (
    DuplicateRulesetVersionError,
    ImmutableRulesetError,
    NoPublishedRulesetError,
    RulesetDiscordLimitError,
    RulesetNotFoundError,
    RulesRepository,
    RulesService,
    validate_ruleset_for_discord,
)
from discord_stats_bot.features.rules.types import (
    RuleAcceptanceRecord,
    RuleAcceptanceResult,
    RulesAcceptanceStatistics,
    RulesComplianceAcceptance,
    RulesComplianceAvailability,
    RulesComplianceResult,
    RulesComplianceStatus,
    RulesComplianceSummary,
    RulesetRecord,
    RulesetStatus,
    RulesetWithAcceptanceCount,
    RulesPublicationConfigurationResult,
    RulesPublicationConfigurationStatus,
    RulesPublicationState,
    RulesPublicationSyncResult,
    RulesPublicationSyncStatus,
)

__all__ = [
    "DuplicateRulesetVersionError",
    "ImmutableRulesetError",
    "NoPublishedRulesetError",
    "RuleAcceptanceRecord",
    "RuleAcceptanceResult",
    "RulesComplianceAcceptance",
    "RulesComplianceAvailability",
    "RulesComplianceRepository",
    "RulesComplianceResult",
    "RulesComplianceService",
    "RulesComplianceStatus",
    "RulesComplianceSummary",
    "RulesAcceptanceStatistics",
    "RulesRepository",
    "RulesService",
    "RulesetDiscordLimitError",
    "RulesetNotFoundError",
    "RulesetRecord",
    "RulesetStatus",
    "RulesetWithAcceptanceCount",
    "RulesPublicationState",
    "RulesPublicationConfigurationResult",
    "RulesPublicationConfigurationStatus",
    "RulesPublicationSyncResult",
    "RulesPublicationSyncStatus",
    "validate_ruleset_for_discord",
]
